#version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./www:/var/www/html
      - ./config/custom.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./config/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - /var/run/php:/var/run/php
      #- ./logs/php-fpm_error.log:/var/log/php-fpm/error.log
    depends_on:
      - redis
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "8092:8092"
    volumes:
      - ./www:/var/www/html
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./config/conf.d:/etc/nginx/conf.d
      - /var/run/php:/var/run/php
     # - ./logs/nginx_access.log:/var/log/nginx/access.log
     # - ./logs/nginx_error.log:/var/log/nginx/error.log
    depends_on:
      - php
    restart: always

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    #volumes:
     # - ./logs/redis.log:/var/log/redis/redis.log
    restart: always
