#version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./www:/var/www/html
      - ./config/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    depends_on:
      - redis
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "8092:8092"
    volumes:
      - ./www:/var/www/html
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./config/conf.d:/etc/nginx/conf.d
      
    depends_on:
      - php
    restart: always

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always