#version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./www:/var/www/html
      - ./custom.ini:/usr/local/etc/php/conf.d/custom.ini
    depends_on:
      - redis
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "8092:8092"
    volumes:
      - ./www:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    restart: always

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always